/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ConferencePage = {
  _id: string;
  _type: "conferencePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  eyebrow: string;
  heading: string;
  facts?: Array<{
    label: string;
    value: string;
    _type: "fact";
    _key: string;
  }>;
  introEyebrow: string;
  introHeading: string;
  introParagraphs: Array<string>;
  themes?: Array<{
    number: string;
    heading: string;
    _type: "theme";
    _key: string;
  }>;
  topics: Array<string>;
  calendar: Array<{
    date: string;
    event: string;
    _type: "calendarRow";
    _key: string;
  }>;
  futureEyebrow: string;
  futureHeading: string;
  futureText: string;
  futureCtaLabel: string;
};

export type JournalsDirectoryPage = {
  _id: string;
  _type: "journalsDirectoryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  eyebrow: string;
  heading: string;
  intro: string;
  journals?: Array<
    {
      _key: string;
    } & Journal
  >;
  noteHeading: string;
  noteText: string;
  noteCtaLabel: string;
  noteCtaHref: string;
};

export type InstitutionalPublicationsPage = {
  _id: string;
  _type: "institutionalPublicationsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  eyebrow: string;
  heading: string;
  intro: string;
  publications?: Array<
    {
      _key: string;
    } & NumberedCard
  >;
  supportEyebrow: string;
  supportHeading: string;
  supportParagraphs: Array<string>;
  contactHeading: string;
  contactText: string;
};

export type LanguageEditingPage = {
  _id: string;
  _type: "languageEditingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  eyebrow: string;
  heading: string;
  intro: string;
  heroCtaLabel: string;
  services?: Array<
    {
      _key: string;
    } & NumberedCard
  >;
  stepsHeading: string;
  steps?: Array<{
    number: string;
    title: string;
    text: string;
    _type: "step";
    _key: string;
  }>;
  supportBand?: Array<{
    eyebrow: string;
    heading: string;
    text: string;
    _type: "supportItem";
    _key: string;
  }>;
  contactHeading: string;
  contactText: string;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  eyebrow: string;
  heading: string;
  intro: string;
  directory?: Array<
    {
      _key: string;
    } & NumberedLinkCard
  >;
  contactEyebrow: string;
  contactHeading: string;
  contactText: string;
};

export type AdvisoryBoardPage = {
  _id: string;
  _type: "advisoryBoardPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  eyebrow: string;
  heading: string;
  intro: string;
  members: Array<
    {
      _key: string;
    } & BoardMember
  >;
  roleEyebrow: string;
  roleHeading: string;
  roleParagraphs: Array<string>;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  eyebrow: string;
  heading: string;
  intro: string;
  narrativeEyebrow: string;
  narrativeHeading: string;
  narrativeParagraphs: Array<string>;
  missionPanel?: Array<{
    eyebrow: string;
    heading: string;
    _type: "panelItem";
    _key: string;
  }>;
  publishListHeading: string;
  publishList: Array<string>;
  partnersHeading: string;
  partnersText: string;
  partnersActions?: Array<
    {
      _key: string;
    } & CtaButton
  >;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  heroEyebrow: string;
  heroHeading: string;
  heroText: string;
  platforms?: Array<
    {
      _key: string;
    } & PlatformCard
  >;
  aboutEyebrow: string;
  aboutHeading: string;
  aboutName: string;
  aboutParagraphs: Array<string>;
  aboutScope?: Array<
    {
      _key: string;
    } & NumberedCard
  >;
  missionVision?: Array<{
    eyebrow: string;
    heading: string;
    _type: "missionVisionItem";
    _key: string;
  }>;
  serviceCards?: Array<
    {
      _key: string;
    } & NumberedLinkCard
  >;
  conferenceBadge: string;
  conferenceHeading: string;
  conferenceText: string;
  authorLinks?: Array<{
    kicker: string;
    heading: string;
    cta: string;
    href: string;
    external?: boolean;
    _type: "authorLink";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  wordmarkStrong: string;
  wordmarkRest: string;
  tagline: string;
  footerBlurb: string;
  copyright: string;
  desktopNavPrimary: Array<
    {
      _key: string;
    } & NavLink
  >;
  aboutDropdown: Array<
    {
      _key: string;
    } & NavLink
  >;
  mobileNav: Array<
    {
      _key: string;
    } & NavLink
  >;
  offices?: Array<
    {
      _key: string;
    } & Office
  >;
  emailInfo: string;
  emailPublisher: string;
  emailLangEditor: string;
};

export type Office = {
  _type: "office";
  country: string;
  heading: string;
  lines: Array<string>;
  footerLines: Array<string>;
};

export type BoardMember = {
  _type: "boardMember";
  number: string;
  name: string;
  affiliation: string;
};

export type Journal = {
  _type: "journal";
  number: string;
  abbreviation: string;
  heading: string;
  text: string;
  href: string;
};

export type PlatformCard = {
  _type: "platformCard";
  heading: string;
  text: string;
  href: string;
  external?: boolean;
  cta: string;
  variant: "blue" | "navy" | "burgundy";
};

export type NumberedLinkCard = {
  _type: "numberedLinkCard";
  number: string;
  heading: string;
  text: string;
  href: string;
  external?: boolean;
};

export type NumberedCard = {
  _type: "numberedCard";
  number: string;
  heading: string;
  text: string;
};

export type NavLink = {
  _type: "navLink";
  label: string;
  href: string;
};

export type CtaButton = {
  _type: "ctaButton";
  label: string;
  href: string;
  variant: "primary" | "secondary";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | ConferencePage
  | JournalsDirectoryPage
  | InstitutionalPublicationsPage
  | LanguageEditingPage
  | ServicesPage
  | AdvisoryBoardPage
  | AboutPage
  | HomePage
  | SanityImageAssetReference
  | Seo
  | SiteSettings
  | Office
  | BoardMember
  | Journal
  | PlatformCard
  | NumberedLinkCard
  | NumberedCard
  | NavLink
  | CtaButton
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{    wordmarkStrong, wordmarkRest, tagline, footerBlurb, copyright,    desktopNavPrimary[]{label, href},    aboutDropdown[]{label, href},    mobileNav[]{label, href},    offices[]{country, heading, lines, footerLines},    emailInfo, emailPublisher, emailLangEditor  }
export type SiteSettingsQueryResult = {
  wordmarkStrong: string;
  wordmarkRest: string;
  tagline: string;
  footerBlurb: string;
  copyright: string;
  desktopNavPrimary: Array<{
    label: string;
    href: string;
  }>;
  aboutDropdown: Array<{
    label: string;
    href: string;
  }>;
  mobileNav: Array<{
    label: string;
    href: string;
  }>;
  offices: Array<{
    country: string;
    heading: string;
    lines: Array<string>;
    footerLines: Array<string>;
  }> | null;
  emailInfo: string;
  emailPublisher: string;
  emailLangEditor: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{    seo,    heroEyebrow, heroHeading, heroText,    platforms[]{heading, text, href, external, cta, variant},    aboutEyebrow, aboutHeading, aboutName, aboutParagraphs,    aboutScope[]{number, heading, text},    missionVision[]{eyebrow, heading},    serviceCards[]{number, heading, text, href, external},    conferenceBadge, conferenceHeading, conferenceText,    authorLinks[]{kicker, heading, cta, href, external}  }
export type HomePageQueryResult = {
  seo: Seo | null;
  heroEyebrow: string;
  heroHeading: string;
  heroText: string;
  platforms: Array<{
    heading: string;
    text: string;
    href: string;
    external: boolean | null;
    cta: string;
    variant: "blue" | "burgundy" | "navy";
  }> | null;
  aboutEyebrow: string;
  aboutHeading: string;
  aboutName: string;
  aboutParagraphs: Array<string>;
  aboutScope: Array<{
    number: string;
    heading: string;
    text: string;
  }> | null;
  missionVision: Array<{
    eyebrow: string;
    heading: string;
  }> | null;
  serviceCards: Array<{
    number: string;
    heading: string;
    text: string;
    href: string;
    external: boolean | null;
  }> | null;
  conferenceBadge: string;
  conferenceHeading: string;
  conferenceText: string;
  authorLinks: Array<{
    kicker: string;
    heading: string;
    cta: string;
    href: string;
    external: boolean | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{    seo, eyebrow, heading, intro,    narrativeEyebrow, narrativeHeading, narrativeParagraphs,    missionPanel[]{eyebrow, heading},    publishListHeading, publishList,    partnersHeading, partnersText,    partnersActions[]{label, href, variant}  }
export type AboutPageQueryResult = {
  seo: Seo | null;
  eyebrow: string;
  heading: string;
  intro: string;
  narrativeEyebrow: string;
  narrativeHeading: string;
  narrativeParagraphs: Array<string>;
  missionPanel: Array<{
    eyebrow: string;
    heading: string;
  }> | null;
  publishListHeading: string;
  publishList: Array<string>;
  partnersHeading: string;
  partnersText: string;
  partnersActions: Array<{
    label: string;
    href: string;
    variant: "primary" | "secondary";
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: advisoryBoardPageQuery
// Query: *[_type == "advisoryBoardPage"][0]{    seo, eyebrow, heading, intro,    members[]{number, name, affiliation},    roleEyebrow, roleHeading, roleParagraphs  }
export type AdvisoryBoardPageQueryResult = {
  seo: Seo | null;
  eyebrow: string;
  heading: string;
  intro: string;
  members: Array<{
    number: string;
    name: string;
    affiliation: string;
  }>;
  roleEyebrow: string;
  roleHeading: string;
  roleParagraphs: Array<string>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: servicesPageQuery
// Query: *[_type == "servicesPage"][0]{    seo, eyebrow, heading, intro,    directory[]{number, heading, text, href, external},    contactEyebrow, contactHeading, contactText  }
export type ServicesPageQueryResult = {
  seo: Seo | null;
  eyebrow: string;
  heading: string;
  intro: string;
  directory: Array<{
    number: string;
    heading: string;
    text: string;
    href: string;
    external: boolean | null;
  }> | null;
  contactEyebrow: string;
  contactHeading: string;
  contactText: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: languageEditingPageQuery
// Query: *[_type == "languageEditingPage"][0]{    seo, eyebrow, heading, intro, heroCtaLabel,    services[]{number, heading, text},    stepsHeading,    steps[]{number, title, text},    supportBand[]{eyebrow, heading, text},    contactHeading, contactText  }
export type LanguageEditingPageQueryResult = {
  seo: Seo | null;
  eyebrow: string;
  heading: string;
  intro: string;
  heroCtaLabel: string;
  services: Array<{
    number: string;
    heading: string;
    text: string;
  }> | null;
  stepsHeading: string;
  steps: Array<{
    number: string;
    title: string;
    text: string;
  }> | null;
  supportBand: Array<{
    eyebrow: string;
    heading: string;
    text: string;
  }> | null;
  contactHeading: string;
  contactText: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: institutionalPublicationsPageQuery
// Query: *[_type == "institutionalPublicationsPage"][0]{    seo, eyebrow, heading, intro,    publications[]{number, heading, text},    supportEyebrow, supportHeading, supportParagraphs,    contactHeading, contactText  }
export type InstitutionalPublicationsPageQueryResult = {
  seo: Seo | null;
  eyebrow: string;
  heading: string;
  intro: string;
  publications: Array<{
    number: string;
    heading: string;
    text: string;
  }> | null;
  supportEyebrow: string;
  supportHeading: string;
  supportParagraphs: Array<string>;
  contactHeading: string;
  contactText: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: journalsDirectoryPageQuery
// Query: *[_type == "journalsDirectoryPage"][0]{    seo, eyebrow, heading, intro,    journals[]{number, abbreviation, heading, text, href},    noteHeading, noteText, noteCtaLabel, noteCtaHref  }
export type JournalsDirectoryPageQueryResult = {
  seo: Seo | null;
  eyebrow: string;
  heading: string;
  intro: string;
  journals: Array<{
    number: string;
    abbreviation: string;
    heading: string;
    text: string;
    href: string;
  }> | null;
  noteHeading: string;
  noteText: string;
  noteCtaLabel: string;
  noteCtaHref: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: conferencePageQuery
// Query: *[_type == "conferencePage"][0]{    seo, eyebrow, heading,    facts[]{label, value},    introEyebrow, introHeading, introParagraphs,    themes[]{number, heading},    topics,    calendar[]{date, event},    futureEyebrow, futureHeading, futureText, futureCtaLabel  }
export type ConferencePageQueryResult = {
  seo: Seo | null;
  eyebrow: string;
  heading: string;
  facts: Array<{
    label: string;
    value: string;
  }> | null;
  introEyebrow: string;
  introHeading: string;
  introParagraphs: Array<string>;
  themes: Array<{
    number: string;
    heading: string;
  }> | null;
  topics: Array<string>;
  calendar: Array<{
    date: string;
    event: string;
  }>;
  futureEyebrow: string;
  futureHeading: string;
  futureText: string;
  futureCtaLabel: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    wordmarkStrong, wordmarkRest, tagline, footerBlurb, copyright,\n    desktopNavPrimary[]{label, href},\n    aboutDropdown[]{label, href},\n    mobileNav[]{label, href},\n    offices[]{country, heading, lines, footerLines},\n    emailInfo, emailPublisher, emailLangEditor\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "homePage"][0]{\n    seo,\n    heroEyebrow, heroHeading, heroText,\n    platforms[]{heading, text, href, external, cta, variant},\n    aboutEyebrow, aboutHeading, aboutName, aboutParagraphs,\n    aboutScope[]{number, heading, text},\n    missionVision[]{eyebrow, heading},\n    serviceCards[]{number, heading, text, href, external},\n    conferenceBadge, conferenceHeading, conferenceText,\n    authorLinks[]{kicker, heading, cta, href, external}\n  }\n': HomePageQueryResult;
    '\n  *[_type == "aboutPage"][0]{\n    seo, eyebrow, heading, intro,\n    narrativeEyebrow, narrativeHeading, narrativeParagraphs,\n    missionPanel[]{eyebrow, heading},\n    publishListHeading, publishList,\n    partnersHeading, partnersText,\n    partnersActions[]{label, href, variant}\n  }\n': AboutPageQueryResult;
    '\n  *[_type == "advisoryBoardPage"][0]{\n    seo, eyebrow, heading, intro,\n    members[]{number, name, affiliation},\n    roleEyebrow, roleHeading, roleParagraphs\n  }\n': AdvisoryBoardPageQueryResult;
    '\n  *[_type == "servicesPage"][0]{\n    seo, eyebrow, heading, intro,\n    directory[]{number, heading, text, href, external},\n    contactEyebrow, contactHeading, contactText\n  }\n': ServicesPageQueryResult;
    '\n  *[_type == "languageEditingPage"][0]{\n    seo, eyebrow, heading, intro, heroCtaLabel,\n    services[]{number, heading, text},\n    stepsHeading,\n    steps[]{number, title, text},\n    supportBand[]{eyebrow, heading, text},\n    contactHeading, contactText\n  }\n': LanguageEditingPageQueryResult;
    '\n  *[_type == "institutionalPublicationsPage"][0]{\n    seo, eyebrow, heading, intro,\n    publications[]{number, heading, text},\n    supportEyebrow, supportHeading, supportParagraphs,\n    contactHeading, contactText\n  }\n': InstitutionalPublicationsPageQueryResult;
    '\n  *[_type == "journalsDirectoryPage"][0]{\n    seo, eyebrow, heading, intro,\n    journals[]{number, abbreviation, heading, text, href},\n    noteHeading, noteText, noteCtaLabel, noteCtaHref\n  }\n': JournalsDirectoryPageQueryResult;
    '\n  *[_type == "conferencePage"][0]{\n    seo, eyebrow, heading,\n    facts[]{label, value},\n    introEyebrow, introHeading, introParagraphs,\n    themes[]{number, heading},\n    topics,\n    calendar[]{date, event},\n    futureEyebrow, futureHeading, futureText, futureCtaLabel\n  }\n': ConferencePageQueryResult;
  }
}
